repos:
  # Python formatters and linters
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10
        files: ^backend/
        args: [--line-length=160]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^backend/
        args:
          - --max-line-length=160
          - --ignore=E127,E251,E302,E501,E261,E262,E265,F401,F403,F405,F841,W293,E128,E303,E305,W292,E122,W391,E111,E117,E301,E125,E222,E226,E201,E203,E202,E721,W503,W504,E272,E126,E225,W291,E211,E231,E722,W191,E712,F523,E402,E306

  # JavaScript/TypeScript formatters and linters
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, json, css, scss, markdown]
        additional_dependencies:
          - prettier@2.8.3
        args:
          - --config=frontend/.prettierrc

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: ^frontend/
        types: [file]
        types_or: [javascript, jsx]
        additional_dependencies:
          - eslint@8.32.0
          - eslint-config-prettier@8.6.0
          - eslint-plugin-react@7.32.1
        args:
          - --config=frontend/.eslintrc.json
          - --fix
          - --max-warnings=0

